### ISSUE TITLE
Remove NUnit dependency

### ISSUE THREAD

**Issue by andreapier** [hibri/Centaur#10]
Is it possibile to remove the `NUnit` dependency?  
There seems to be no `NUnit` class usage inside `IISExpressHost` so it should be safe to just remove the dependency.  
  
Thanks
Andrea

**Comment by hibri** [comment]
Thanks Andrea. 
Good spot. Will update it soon. Can you send a PR in the meantime if possible?

**Comment by andreapier** [comment]
Done sir.  
Look at #11!  
I just want to state it again: review it please, this is my very first PR!  
Also, it is the first time I work with `nuspec` files so please tell me if anything is wrong.  
Thanks!

**Comment by hibri** [comment]
Thanks @andreapier :) I've merged it, but have to work on the build a bit. I don't have a windows box anymore :) will publish it soon
